//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FORUM_WEB_2._0.Models.FrameWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int ID_BaoCao { get; set; }
        public string NguoiBaoCao { get; set; }
        public string NoiDung { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
