//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FORUM_WEB_2._0.Models.FrameWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top_BinhLuan
    {
        public int ID_BaiDang { get; set; }
        public Nullable<int> ID_BinhLuan { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
        public virtual BinhLuan BinhLuan { get; set; }
    }
}
